import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
    vi: {
        // Navbar
        home: 'Trang chủ',
        products: 'Sản phẩm',
        categories: 'Danh mục',
        about: 'Về chúng tôi',
        login: 'Đăng nhập',
        logout: 'Đăng xuất',
        cart: 'Giỏ hàng',
        profile: 'Hồ sơ',
        myProfile: 'Hồ sơ của tôi',
        back: 'QUAY LẠI',
        search: 'Tìm kiếm',
        guest: 'Khách',
        error: 'Có lỗi xảy ra, vui lòng thử lại.',
        dateFormat: 'vi-VN',
        
        // Hero
        heroLabel: 'Nền tảng thuê thời trang',
        heroTitle: 'Thuê Outfit Cao Cấp Cho Mọi Dịp',
        heroSubtitle: 'Vest, sneaker, váy và phụ kiện thời trang dành cho giới trẻ hiện đại. Trải nghiệm thời trang cao cấp với chi phí hợp lý.',
        rentNow: 'Thuê ngay',
        exploreProducts: 'Khám phá sản phẩm',
        from: 'Từ',
        perDay: 'ngày',
        scrollDown: 'Cuộn xuống',

        // Sections
        collection: 'Bộ sưu tập',
        exploreCategories: 'Khám Phá Danh Mục',
        viewMore: 'Xem thêm',
        featured: 'Nổi bật',
        popularProducts: 'Sản Phẩm Được Yêu Thích',
        viewAllProducts: 'Xem tất cả sản phẩm',
        new: 'Mới',
        trending: 'Xu hướng',
        
        // Why Choose Us
        whyChooseUs: 'Tại sao chọn chúng tôi',
        perfectService: 'Dịch Vụ Hoàn Hảo',
        premiumQuality: 'Chất lượng cao cấp',
        premiumQualityDesc: 'Tất cả sản phẩm đều được kiểm tra kỹ lưỡng và giặt hấp chuyên nghiệp sau mỗi lần thuê.',
        fastDelivery: 'Giao hàng nhanh',
        fastDeliveryDesc: 'Giao hàng trong 2-4 giờ tại nội thành và 24 giờ toàn quốc. Miễn phí ship đơn từ 500K.',
        easyReturns: 'Đổi trả dễ dàng',
        easyReturnsDesc: 'Hỗ trợ đổi size miễn phí trong 24 giờ. Chính sách hoàn tiền linh hoạt.',
        reasonablePrice: 'Giá cả hợp lý',
        reasonablePriceDesc: 'Thuê outfit cao cấp với chi phí chỉ từ 10% giá mua. Tiết kiệm thông minh.',
        
        // Testimonials
        reviews: 'Đánh giá',
        whatCustomersSay: 'Khách Hàng Nói Gì',
        customer: 'Khách hàng',
        rentalCustomer: 'Khách hàng thuê đồ',
        noReviews: 'Chưa có đánh giá nào từ khách hàng.',

        // Products Page
        fashionCollection: 'Bộ Sưu Tập Thời Trang',
        rentForOccasions: 'Thuê trang phục cao cấp cho mọi dịp quan trọng',
        exploreNow: 'Khám phá ngay',
        searchPlaceholder: 'Tìm kiếm trang phục cao cấp...',
        sortBy: 'Sắp xếp theo',
        newest: 'Mới nhất',
        priceLowHigh: 'Giá: Thấp đến Cao',
        priceHighLow: 'Giá: Cao đến Thấp',
        all: 'Tất cả',
        priceRange: 'Khoảng giá',
        status: 'Trạng thái',
        ready: 'Sẵn sàng',
        newArrivals: 'Hàng mới về',
        resetFilters: 'Đặt lại bộ lọc',
        showing: 'Đang hiển thị',
        productsLabel: 'sản phẩm',
        loadingCollection: 'Đang tải bộ sưu tập...',
        inStock: 'Còn hàng',
        outOfStock: 'Hết hàng',
        addedToCart: 'Đã thêm {name} vào giỏ hàng!',

        // Product Detail
        productLoading: 'Đang tải thông tin sản phẩm...',
        productNotFound: 'Không tìm thấy sản phẩm này.',
        description: 'Mô tả chi tiết',
        reviewsCount: 'Đánh giá ({count})',
        policy: 'Chính sách',
        writeReview: 'Viết đánh giá của bạn',
        productQuality: 'Chất lượng sản phẩm:',
        excellent: 'Tuyệt vời',
        veryGood: 'Rất tốt',
        normal: 'Bình thường',
        poor: 'Kém',
        veryPoor: 'Rất kém',
        shareExperience: 'Chia sẻ trải nghiệm của bạn về sản phẩm này...',
        submitReview: 'Gửi đánh giá',
        submitting: 'Đang gửi...',
        customerReviews: 'Đánh giá từ khách hàng ({count})',
        noProductReviews: 'Chưa có đánh giá nào cho sản phẩm này.',
        policy1: 'Thời gian thuê tính theo gói 24h kể từ lúc nhận đồ.',
        policy2: 'Vui lòng kiểm tra kỹ tình trạng trang phục khi nhận.',
        policy3: 'Sản phẩm đã được giặt là và khử khuẩn sạch sẽ.',
        policy4: 'Hỗ trợ đổi trả size trong vòng 2 giờ đầu tiên.',
        noDescription: 'Chưa có mô tả chi tiết cho sản phẩm này.',
        enterReviewContent: 'Vui lòng nhập nội dung đánh giá.',
        thankYouReview: 'Cảm ơn bạn đã đánh giá sản phẩm!',
        defaultDescription: 'Trải nghiệm sự thanh lịch vượt thời gian với sản phẩm này.',
        similarProducts: 'Sản phẩm tương tự',
        viewAngle: 'góc nhìn',
        thumbnail: 'ảnh nhỏ',
        qtyShort: 'SL',

        // Product Info
        premiumProduct: 'Sản phẩm cao cấp',
        size: 'Kích thước (Size)',
        color: 'Màu sắc',
        quantity: 'Số lượng',
        rentalPeriod: 'Thời gian thuê',
        startDate: 'Ngày bắt đầu',
        endDate: 'Ngày kết thúc',
        total: 'Tổng cộng:',
        days: 'ngày',
        priceSummary: 'Tạm tính chi phí',
        pricePerDay: 'Giá thuê (mỗi ngày)',
        totalRentalFee: 'Tổng tiền thuê ({days} ngày x {quantity} cái)',
        totalEstimated: 'Tổng cộng tạm tính',
        rentNowUpper: 'THUÊ NGAY',
        addToCart: 'Thêm vào giỏ hàng',
        notAvailable: 'Không khả dụng',
        safetyPolicy: 'Chính sách bảo đảm',
        safetyPolicyDesc: 'Sản phẩm được kiểm tra kỹ lưỡng và khử khuẩn 100% trước khi giao đến tay khách hàng.',
        selectSizeAlert: 'Vui lòng chọn kích thước (size) sản phẩm.',
        selectColorAlert: 'Vui lòng chọn màu sắc sản phẩm.',
        selectRentalPeriodAlert: 'Vui lòng chọn thời gian thuê (ngày bắt đầu và kết thúc).',
        endDateBeforeStartAlert: 'Ngày kết thúc không được trước ngày bắt đầu thuê.',

        // Cart Page
        yourCart: 'Giỏ hàng của bạn',
        emptyCart: 'Giỏ hàng của bạn đang trống',
        emptyCartDesc: 'Hãy khám phá những bộ sưu tập cao cấp của chúng tôi và chọn cho mình bộ đồ ưng ý nhất.',
        continueShopping: 'Tiếp tục mua sắm',
        productsInCart: 'sản phẩm trong giỏ hàng',
        deleteAll: 'Xóa tất cả',
        fashion: 'Thời trang',
        rentalDuration: 'Thời gian thuê: {days} ngày',
        orderSummary: 'Tóm tắt đơn hàng',
        subtotal: 'Tạm tính',
        depositFee: 'Phí đặt cọc (20%)',
        shippingFee: 'Phí vận chuyển',
        discountCode: 'Mã giảm giá',
        apply: 'Áp dụng',
        totalAmount: 'Tổng cộng',
        proceedToCheckout: 'Tiến hành thanh toán',
        continueRental: 'Tiếp tục thuê đồ',
        securePayment: 'Thanh toán an toàn 100%',
        returnPolicyNote: '* Tất cả trang phục phải được trả lại trong tình trạng ban đầu. Trả trễ hạn có thể phát sinh thêm phí theo quy định.',
        confirmDelete: 'Bạn có chắc chắn muốn xóa sản phẩm này khỏi giỏ hàng?',
        confirmClearCart: 'Bạn có chắc chắn muốn xóa toàn bộ giỏ hàng?',

        // Login
        elevateStyle: 'Nâng Tầm Phong Cách Của Bạn',
        premiumPlatform: 'Nền Tảng Cho Thuê Thời Trang Cao Cấp',
        welcomeBack: 'Chào Mừng Trở Lại',
        loginToContinue: 'Đăng nhập để tiếp tục thuê những bộ đồ yêu thích',
        emailAddress: 'Địa chỉ Email',
        password: 'Mật khẩu',
        enterPassword: 'Nhập mật khẩu của bạn',
        rememberMe: 'Ghi nhớ đăng nhập',
        forgotPassword: 'Quên mật khẩu?',
        processing: 'Đang xử lý...',
        or: 'HOẶC',
        continueWithGoogle: 'Tiếp tục với Google',
        continueWithFacebook: 'Tiếp tục với Facebook',
        noAccount: 'Chưa có tài khoản?',
        signUpNow: 'Đăng ký ngay',
        alreadyHaveAccount: 'Đã có tài khoản?',
        
        // Register
        discoverStyle: 'Khám Phá Phong Cách Mới',
        community: 'Cộng Đồng Thuê Thời Trang Cao Cấp',
        createAccount: 'Tạo Tài Khoản',
        registerToExperience: 'Đăng ký để bắt đầu trải nghiệm thời trang cao cấp',
        fullName: 'Họ và Tên',
        phoneNumber: 'Số Điện Thoại',
        confirmPassword: 'Xác nhận mật khẩu',
        enterConfirmPassword: 'Nhập lại mật khẩu',
        passwordMismatch: 'Mật khẩu xác nhận không khớp',
        namePlaceholder: 'Nguyễn Văn A',
        emailPlaceholder: 'email@cua-ban.com',
        phonePlaceholder: '0123 456 789',
        
        // Profile & Orders
        myProfile: 'Hồ sơ của tôi',
        myRentals: 'Đơn thuê của tôi',
        manageRentals: 'Quản lý và theo dõi các đơn hàng thuê của bạn',
        searchOrderPlaceholder: 'Tìm kiếm theo mã đơn hoặc tên sản phẩm...',
        allOrders: 'Tất cả đơn hàng',
        pending: 'Chờ xử lý',
        approved: 'Đã xác nhận',
        renting: 'Đang giao hàng',
        returned: 'Đã trả đồ',
        orderId: 'Mã đơn',
        returnDeadline: 'Hạn trả đồ',
        paymentStatus: 'Thanh toán',
        payOnDelivery: 'Khi nhận đồ',
        paid: 'Đã thanh toán',
        viewDetail: 'Xem chi tiết',
        trackOrder: 'Theo dõi',
        totalPrice: 'Tổng tiền',
        orderNotFound: 'Không tìm thấy đơn hàng',
        noRentalHistory: 'Bạn chưa có đơn thuê nào trong lịch sử.',
        wishlist: 'Danh sách yêu thích',
        addresses: 'Địa chỉ',
        paymentMethods: 'Phương thức thanh toán',
        settings: 'Cài đặt',
        underDevelopment: 'Đang phát triển',
        featureComingSoon: 'Tính năng này sẽ sớm ra mắt.',
        rentalDetail: 'Chi tiết đơn thuê',
        shippingInfo: 'Thông tin giao hàng',
        recipient: 'Người nhận',
        deliveryMethod: 'Hình thức',
        shipToHome: 'Giao tận nơi',
        pickAtStore: 'Nhận tại cửa hàng',
        rentedProducts: 'Sản phẩm thuê',
        loadingDetails: 'Đang tải chi tiết...',
        failedToLoadDetails: 'Không thể tải chi tiết đơn hàng.',
        
        // Rental History
        rentalHistory: 'Lịch sử thuê đồ',
        loadingRentalHistory: 'Đang tải lịch sử thuê...',
        noOrdersYet: 'Bạn chưa có đơn thuê nào',
        exploreCollections: 'Khám phá các bộ sưu tập của chúng tôi và bắt đầu thuê ngay!',
        viewProducts: 'Xem sản phẩm',
        orderNumber: 'Đơn hàng',
        cancelled: 'Đã hủy',
        approvedStatus: 'Đã duyệt',
        pendingStatus: 'Chờ duyệt',
        
        // About
        aboutUs: 'Về Chúng Tôi',
        aboutHeroTitle: 'Thời trang cao cấp dành cho mọi người',
        ourStory: 'Câu Chuyện Của Chúng Tôi',
        storyP1: 'Luxe Rental được thành lập với sứ mệnh mang thời trang cao cấp đến gần hơn với mọi người. Chúng tôi tin rằng vẻ đẹp xa xỉ không chỉ dành cho việc sở hữu, mà là trải nghiệm mà ai cũng có thể tiếp cận.',
        storyP2: 'Bộ sưu tập của chúng tôi bao gồm váy cưới cao cấp, đầm dạ hội, vest sang trọng và phụ kiện thời trang. Mỗi sản phẩm đều được tuyển chọn kỹ lưỡng để đảm bảo chất lượng và phong cách vượt thời gian.',
        storyP3: 'Chúng tôi cam kết với thời trang bền vững. Việc thuê thay vì mua giúp giảm thiểu lãng phí và bảo vệ môi trường, đồng thời giúp bạn tự do thể hiện phong cách cá nhân.',
        mission: 'Sứ Mệnh',
        missionDesc: 'Mang thời trang cao cấp đến gần hơn với mọi người thông qua dịch vụ thuê đồ chuyên nghiệp và giá cả hợp lý.',
        vision: 'Tầm Nhìn',
        visionDesc: 'Trở thành nền tảng cho thuê thời trang cao cấp uy tín nhất, tiên phong trong phong cách bền vững.',
        coreValues: 'Giá Trị Cốt Lõi',
        coreValuesDesc: 'Chất lượng, bền vững, trải nghiệm khách hàng và đổi mới là những gì định hình thương hiệu của chúng tôi.',
        perfectService: 'Dịch Vụ Hoàn Hảo',
        rentalProcess: 'Quy Trình Thuê Đồ',
        step1: 'Bước 1',
        step1Title: 'Chọn Sản Phẩm',
        step1Desc: 'Khám phá bộ sưu tập thời trang cao cấp',
        step2: 'Bước 2',
        step2Title: 'Đặt Thuê',
        step2Desc: 'Thêm sản phẩm yêu thích vào giỏ hàng',
        step3: 'Bước 3',
        step3Title: 'Chọn Ngày Thuê',
        step3Desc: 'Chọn thời gian thuê và ngày giao hàng',
        step4: 'Bước 4',
        step4Title: 'Nhận & Trả Hàng',
        step4Desc: 'Giao nhận tận nơi miễn phí',
        
        // Categories Page
        exploreCategoriesTitle: 'Khám Phá Danh Mục Thời Trang',
        exploreCategoriesSubtitle: 'Khám phá các bộ sưu tập cho thuê cao cấp cho mọi dịp lễ',
        viewCollection: 'Xem Bộ Sưu Tập',
        searchCategoryPlaceholder: 'Tìm kiếm danh mục...',
        allCategoriesTab: 'Tất cả danh mục',
        popularTab: 'Phổ biến',
        latestTab: 'Mới nhất',
        luxuryCollectionTab: 'Bộ sưu tập Luxury',
        rentalCategories: 'Danh Mục Thuê',
        showingCategories: 'Hiển thị {count} danh mục',
        exploreCategoryLink: 'Khám phá bộ sưu tập',
        happyCustomers: 'Khách hàng hài lòng',
        successfulRentals: 'Lượt thuê thành công',
        averageRating: 'Đánh giá trung bình',
        luxuryProductsCount: 'Sản phẩm Luxury',

        // Checkout Page
        checkout: 'Thanh toán',
        customerInfo: 'Thông tin khách hàng',
        shippingAddress: 'Địa chỉ giao hàng',
        specialRequests: 'Yêu cầu đặc biệt',
        specialRequestsPlaceholder: 'Ghi chú thêm cho cửa hàng hoặc shipper...',
        rentalPeriodNote: 'Thời gian thuê được lấy từ lựa chọn sản phẩm trong giỏ hàng.',
        homeDelivery: 'Giao hàng tận nơi',
        homeDeliveryDesc: 'Giao đến địa chỉ của bạn trong vòng 2-4 giờ',
        pickupAtStore: 'Nhận tại cửa hàng',
        pickupAtStoreDesc: 'Lấy đồ trực tiếp tại showroom (Miễn phí)',
        agreeTerms: 'Tôi đồng ý với các {terms} và {privacy}',
        termsOfService: 'điều khoản thuê đồ',
        privacyPolicy: 'chính sách bảo mật',
        cod: 'Thanh toán khi nhận hàng',
        codDesc: 'Trả tiền mặt khi Shipper giao đồ tới',
        momo: 'Ví điện tử MoMo',
        momoDesc: 'Thanh toán nhanh chóng qua ứng dụng',
        vnpay: 'Cổng VNPay',
        vnpayDesc: 'Hỗ trợ tất cả các ngân hàng Việt Nam',
        creditCard: 'Thẻ Tín dụng / Ghi nợ',
        creditCardDesc: 'Visa, Mastercard, JCB, Amex',
        rentalFee: 'Tiền thuê',
        confirmCheckout: 'Xác nhận đặt thuê',
        securePaymentNote: 'Thanh toán an toàn & Bảo mật thông tin khách hàng 100%',
        checkoutSuccess: 'Đặt hàng thành công!',
        checkoutSuccessTitle: 'Đặt hàng thành công!',
        checkoutSuccessDesc: 'Cảm ơn bạn đã tin tưởng Luxe Rent. Đơn hàng của bạn đang được xử lý.',
        checkEmailNotice: 'Một email xác nhận chi tiết đơn hàng đã được gửi đến địa chỉ email của bạn. Vui lòng kiểm tra hộp thư (bao gồm cả thư rác).',
        emptyCartAlert: 'Giỏ hàng của bạn đang trống.',
        nameRequired: 'Vui lòng nhập họ và tên.',
        emailRequired: 'Vui lòng nhập địa chỉ email.',
        phoneRequired: 'Vui lòng nhập số điện thoại.',
        addressRequired: 'Vui lòng nhập địa chỉ giao hàng.',
        termsRequired: 'Bạn cần đồng ý với điều khoản và chính sách để tiếp tục đặt thuê.',
        preparingOrder: 'Đang chuẩn bị đơn hàng của bạn...',
        addressPlaceholder: 'Số nhà, tên đường, phường/xã, quận/huyện...',
        paymentMethod: 'Phương thức thanh toán',
        bankTransfer: 'Chuyển khoản ngân hàng',
        bankTransferDesc: 'Thanh toán qua mã VietQR chuẩn NAPAS 247',
        scanQRCode: 'Quét mã QR để thanh toán',
        qrPaymentInstruction: 'Sử dụng ứng dụng ngân hàng hoặc ví điện tử để quét mã dưới đây',
        paymentInfo: 'Thông tin thanh toán',
        recipient: 'Người nhận',
        shippingAddress: 'Địa chỉ giao hàng',
        paymentStatus: 'Trạng thái thanh toán',
        rentedProducts: 'Sản phẩm thuê',
        suggestedProducts: 'Sản phẩm gợi ý dành cho bạn',
        addToWishlist: 'Thêm vào danh sách yêu thích',
        removeFromWishlist: 'Xóa khỏi danh sách yêu thích',
        selectSize: 'Chọn kích cỡ',
        
        // Footer
        footerDesc: 'Nền tảng cho thuê thời trang cao cấp hàng đầu Việt Nam. Trải nghiệm phong cách sống thời thượng với chi phí hợp lý.',
        support: 'Hỗ trợ',
        contact: 'Liên hệ',
        copyright: '© 2024 LUXE RENT. Bản quyền được bảo lưu.',
        terms: 'Điều khoản sử dụng',
        privacy: 'Chính sách bảo mật',
        howToRent: 'Hướng dẫn thuê',
        returnPolicy: 'Chính sách đổi trả',
        sizeGuide: 'Bảng size',
        faq: 'Câu hỏi thường gặp',
        
        // Colors
        color_blue: 'Xanh dương',

        // Category Data Mapping
        'Váy cưới': 'Váy cưới',
        'Đầm dạ hội': 'Đầm dạ hội',
        'Vest nam': 'Vest nam',
        'Vest sang trọng': 'Vest sang trọng',
        'Phụ kiện': 'Phụ kiện',
        'Giày & Sneaker': 'Giày & Sneaker',
        'Thời trang nữ': 'Thời trang nữ',
        'Thời trang nam': 'Thời trang nam',
        'Hàng mới về': 'Hàng mới về',
        'Sản phẩm': 'Sản phẩm',
        'Danh mục': 'Danh mục',
        'Váy': 'Váy',
        'Vest': 'Vest',
        'Sneaker': 'Sneaker',
        'Streetwear': 'Streetwear',
        'footerAddress': '123 Nguyễn Huệ, Q.1, TP.HCM',
    },
    en: {
        // Navbar
        home: 'Home',
        products: 'Products',
        categories: 'Categories',
        about: 'About Us',
        login: 'Login',
        logout: 'Logout',
        cart: 'Cart',
        profile: 'Profile',
        myProfile: 'My Profile',
        back: 'BACK',
        search: 'Search',
        guest: 'Guest',
        error: 'An error occurred, please try again.',
        dateFormat: 'en-US',
        
        // Hero
        heroLabel: 'Fashion Rental Platform',
        heroTitle: 'Rent Premium Outfits For Every Occasion',
        heroSubtitle: 'Suits, sneakers, dresses, and accessories for modern youth. Experience high-end fashion at reasonable prices.',
        rentNow: 'Rent Now',
        exploreProducts: 'Explore Products',
        from: 'From',
        perDay: 'day',
        scrollDown: 'Scroll down',

        // Sections
        collection: 'Collection',
        exploreCategories: 'Explore Categories',
        viewMore: 'View More',
        featured: 'Featured',
        popularProducts: 'Popular Products',
        viewAllProducts: 'View All Products',
        new: 'New',
        trending: 'Trending',

        // Why Choose Us
        whyChooseUs: 'Why Choose Us',
        perfectService: 'Perfect Service',
        premiumQuality: 'Premium Quality',
        premiumQualityDesc: 'All products are carefully inspected and professionally dry cleaned after each rental.',
        fastDelivery: 'Fast Delivery',
        fastDeliveryDesc: 'Delivery in 2-4 hours locally and 24 hours nationwide. Free shipping on orders over 500K.',
        easyReturns: 'Easy Returns',
        easyReturnsDesc: 'Free size exchange support within 24 hours. Flexible refund policy.',
        reasonablePrice: 'Reasonable Price',
        reasonablePriceDesc: 'Rent premium outfits at only 10% of the purchase price. Smart savings.',

        // Testimonials
        reviews: 'Reviews',
        whatCustomersSay: 'What Customers Say',
        customer: 'Customer',
        rentalCustomer: 'Rental Customer',
        noReviews: 'No reviews from customers yet.',

        // Products Page
        fashionCollection: 'Fashion Collection',
        rentForOccasions: 'Rent premium outfits for all important occasions',
        exploreNow: 'Explore Now',
        searchPlaceholder: 'Search premium outfits...',
        sortBy: 'Sort by',
        newest: 'Newest',
        priceLowHigh: 'Price: Low to High',
        priceHighLow: 'Price: High to Low',
        all: 'All',
        priceRange: 'Price Range',
        status: 'Status',
        ready: 'Ready',
        newArrivals: 'New Arrivals',
        resetFilters: 'Reset Filters',
        showing: 'Showing',
        productsLabel: 'products',
        loadingCollection: 'Loading collection...',
        inStock: 'In Stock',
        outOfStock: 'Out of Stock',
        addedToCart: 'Added {name} to cart!',

        // Product Detail
        productLoading: 'Loading product information...',
        productNotFound: 'Product not found.',
        description: 'Detailed Description',
        reviewsCount: 'Reviews ({count})',
        policy: 'Policy',
        writeReview: 'Write your review',
        productQuality: 'Product Quality:',
        excellent: 'Excellent',
        veryGood: 'Very Good',
        normal: 'Normal',
        poor: 'Poor',
        veryPoor: 'Very Poor',
        shareExperience: 'Share your experience with this product...',
        submitReview: 'Submit Review',
        submitting: 'Submitting...',
        customerReviews: 'Customer Reviews ({count})',
        noProductReviews: 'No reviews for this product yet.',
        policy1: 'Rental time is calculated in 24h packages from receipt.',
        policy2: 'Please check the outfit condition carefully upon receipt.',
        policy3: 'The product has been professionally cleaned and sanitized.',
        policy4: 'Size exchange support within the first 2 hours.',
        noDescription: 'No detailed description for this product yet.',
        enterReviewContent: 'Please enter review content.',
        thankYouReview: 'Thank you for your review!',
        defaultDescription: 'Experience timeless elegance with this product.',
        similarProducts: 'Similar Products',
        viewAngle: 'view',
        thumbnail: 'thumbnail',
        qtyShort: 'Qty',

        // Product Info
        premiumProduct: 'Premium Product',
        size: 'Size',
        color: 'Color',
        quantity: 'Quantity',
        rentalPeriod: 'Rental Period',
        startDate: 'Start Date',
        endDate: 'End Date',
        total: 'Total:',
        days: 'days',
        priceSummary: 'Estimated Cost',
        pricePerDay: 'Rental Price (per day)',
        totalRentalFee: 'Total Rental Fee ({days} days x {quantity} items)',
        totalEstimated: 'Estimated Total',
        rentNowUpper: 'RENT NOW',
        addToCart: 'Add to Cart',
        notAvailable: 'Not Available',
        safetyPolicy: 'Safety Policy',
        safetyPolicyDesc: 'Products are thoroughly inspected and 100% sanitized before delivery.',
        selectSizeAlert: 'Please select product size.',
        selectColorAlert: 'Please select product color.',
        selectRentalPeriodAlert: 'Please select rental period (start and end date).',
        endDateBeforeStartAlert: 'End date cannot be before start date.',

        // Cart Page
        yourCart: 'Your Cart',
        emptyCart: 'Your cart is empty',
        emptyCartDesc: 'Explore our premium collections and pick your favorite outfits.',
        continueShopping: 'Continue Shopping',
        productsInCart: 'products in cart',
        deleteAll: 'Delete All',
        fashion: 'Fashion',
        rentalDuration: 'Rental duration: {days} days',
        orderSummary: 'Order Summary',
        subtotal: 'Subtotal',
        depositFee: 'Deposit Fee (20%)',
        shippingFee: 'Shipping Fee',
        discountCode: 'Discount Code',
        apply: 'Apply',
        totalAmount: 'Total',
        proceedToCheckout: 'Proceed to Checkout',
        continueRental: 'Continue Rental',
        securePayment: '100% Secure Payment',
        returnPolicyNote: '* All outfits must be returned in original condition. Late returns may incur additional fees as per regulations.',
        confirmDelete: 'Are you sure you want to remove this item from your cart?',
        confirmClearCart: 'Are you sure you want to clear your entire cart?',

        // Login
        elevateStyle: 'Elevate Your Style',
        premiumPlatform: 'Premium Fashion Rental Platform',
        welcomeBack: 'Welcome Back',
        loginToContinue: 'Log in to continue renting your favorite outfits',
        emailAddress: 'Email Address',
        password: 'Password',
        enterPassword: 'Enter your password',
        rememberMe: 'Remember me',
        forgotPassword: 'Forgot password?',
        processing: 'Processing...',
        or: 'OR',
        continueWithGoogle: 'Continue with Google',
        continueWithFacebook: 'Continue with Facebook',
        noAccount: "Don't have an account?",
        signUpNow: 'Sign up now',
        alreadyHaveAccount: 'Already have an account?',

        // Register
        discoverStyle: 'Discover New Style',
        community: 'Premium Fashion Rental Community',
        createAccount: 'Create Account',
        registerToExperience: 'Register to start experiencing high-end fashion',
        fullName: 'Full Name',
        phoneNumber: 'Phone Number',
        confirmPassword: 'Confirm Password',
        enterConfirmPassword: 'Re-enter password',
        passwordMismatch: 'Passwords do not match',
        namePlaceholder: 'John Doe',
        emailPlaceholder: 'email@your-email.com',
        phonePlaceholder: '0123 456 789',

        // Profile & Orders
        myProfile: 'My Profile',
        myRentals: 'My Rentals',
        manageRentals: 'Manage and track your rental orders',
        searchOrderPlaceholder: 'Search by order ID or product name...',
        allOrders: 'All Orders',
        pending: 'Pending',
        approved: 'Approved',
        renting: 'Delivering',
        returned: 'Returned',
        orderId: 'Order ID',
        returnDeadline: 'Return Deadline',
        paymentStatus: 'Payment',
        payOnDelivery: 'Pay on Delivery',
        paid: 'Paid',
        viewDetail: 'View Detail',
        trackOrder: 'Track Order',
        totalPrice: 'Total Price',
        orderNotFound: 'Order Not Found',
        noRentalHistory: 'You have no rental history.',
        wishlist: 'Wishlist',
        addresses: 'Addresses',
        paymentMethods: 'Payment Methods',
        settings: 'Settings',
        underDevelopment: 'Under Development',
        featureComingSoon: 'This feature is coming soon.',
        rentalDetail: 'Rental Detail',
        shippingInfo: 'Shipping Information',
        recipient: 'Recipient',
        deliveryMethod: 'Delivery Method',
        shipToHome: 'Ship to Home',
        pickAtStore: 'Pick up at Store',
        rentedProducts: 'Rented Products',
        loadingDetails: 'Loading details...',
        failedToLoadDetails: 'Failed to load order details.',

        // Rental History
        rentalHistory: 'Rental History',
        loadingRentalHistory: 'Loading rental history...',
        noOrdersYet: 'You have no orders yet',
        exploreCollections: 'Explore our collections and start renting now!',
        viewProducts: 'View Products',
        orderNumber: 'Order',
        cancelled: 'Cancelled',
        approvedStatus: 'Approved',
        pendingStatus: 'Pending',

        // About
        aboutUs: 'About Us',
        aboutHeroTitle: 'Premium fashion for everyone',
        ourStory: 'Our Story',
        storyP1: 'Luxe Rental was founded with the mission of bringing high-end fashion closer to everyone. We believe that luxury beauty is not just about owning, but an experience that everyone can access.',
        storyP2: 'Our collection includes premium wedding dresses, evening gowns, elegant suits, and fashion accessories. Each product is carefully selected to ensure timeless quality and style.',
        storyP3: 'We are committed to sustainable fashion. Renting instead of buying helps minimize waste and protect the environment, while giving you the freedom to express your personal style.',
        mission: 'Mission',
        missionDesc: 'Bringing high-end fashion closer to everyone through professional rental services and reasonable prices.',
        vision: 'Vision',
        visionDesc: 'To become the most prestigious luxury fashion rental platform, pioneering in sustainable style.',
        coreValues: 'Core Values',
        coreValuesDesc: 'Quality, sustainability, customer experience, and innovation are what define our brand.',
        perfectService: 'Perfect Service',
        rentalProcess: 'Rental Process',
        step1: 'Step 1',
        step1Title: 'Choose Product',
        step1Desc: 'Explore our luxury fashion collection',
        step2: 'Step 2',
        step2Title: 'Book Rental',
        step2Desc: 'Add your favorite products to cart',
        step3: 'Step 3',
        step3Title: 'Select Dates',
        step3Desc: 'Choose rental period and delivery date',
        step4: 'Step 4',
        step4Title: 'Receive & Return',
        step4Desc: 'Free doorstep delivery and pickup',

        // Categories Page
        exploreCategoriesTitle: 'Explore Fashion Categories',
        exploreCategoriesSubtitle: 'Discover premium rental collections for every occasion',
        viewCollection: 'View Collection',
        searchCategoryPlaceholder: 'Search categories...',
        allCategoriesTab: 'All Categories',
        popularTab: 'Popular',
        latestTab: 'Latest',
        luxuryCollectionTab: 'Luxury Collection',
        rentalCategories: 'Rental Categories',
        showingCategories: 'Showing {count} categories',
        exploreCategoryLink: 'Explore collection',
        happyCustomers: 'Happy customers',
        successfulRentals: 'Successful rentals',
        averageRating: 'Average rating',
        luxuryProductsCount: 'Luxury products',

        // Checkout Page
        checkout: 'Checkout',
        customerInfo: 'Customer Information',
        shippingAddress: 'Shipping Address',
        specialRequests: 'Special Requests',
        specialRequestsPlaceholder: 'Additional notes for the shop or courier...',
        rentalPeriodNote: 'Rental duration is taken from the product selection in your cart.',
        homeDelivery: 'Home Delivery',
        homeDeliveryDesc: 'Delivered to your address within 2-4 hours',
        pickupAtStore: 'Pick up at store',
        pickupAtStoreDesc: 'Pick up directly at our showroom (Free)',
        agreeTerms: 'I agree to the {terms} and {privacy}',
        termsOfService: 'terms of service',
        privacyPolicy: 'privacy policy',
        cod: 'Cash on Delivery',
        codDesc: 'Pay cash when the courier arrives',
        momo: 'MoMo E-wallet',
        momoDesc: 'Quick payment via the app',
        vnpay: 'VNPay Gateway',
        vnpayDesc: 'Supports all Vietnamese banks',
        creditCard: 'Credit / Debit Card',
        creditCardDesc: 'Visa, Mastercard, JCB, Amex',
        rentalFee: 'Rental Fee',
        confirmCheckout: 'Confirm Order',
        securePaymentNote: '100% Secure Payment & Customer Data Privacy',
        checkoutSuccess: 'Order successful!',
        checkoutSuccessTitle: 'Order Successful!',
        checkoutSuccessDesc: 'Thank you for choosing Luxe Rent. Your order is being processed.',
        checkEmailNotice: 'A confirmation email with order details has been sent to your email address. Please check your inbox (including spam).',
        emptyCartAlert: 'Your cart is empty.',
        nameRequired: 'Please enter your full name.',
        emailRequired: 'Please enter your email address.',
        phoneRequired: 'Please enter your phone number.',
        addressRequired: 'Please enter your shipping address.',
        termsRequired: 'You need to agree to the terms and policy to continue.',
        preparingOrder: 'Preparing your order...',
        addressPlaceholder: 'Street, ward, district, city...',
        paymentMethod: 'Payment Method',
        bankTransfer: 'Bank Transfer',
        bankTransferDesc: 'Payment via NAPAS 247 VietQR code',
        scanQRCode: 'Scan QR Code to pay',
        qrPaymentInstruction: 'Use your banking app or e-wallet to scan the QR code below',
        paymentInfo: 'Payment Information',
        recipient: 'Recipient',
        shippingAddress: 'Shipping Address',
        paymentStatus: 'Payment Status',
        rentedProducts: 'Rented Products',
        suggestedProducts: 'Suggested products for you',
        addToWishlist: 'Add to wishlist',
        removeFromWishlist: 'Remove from wishlist',
        selectSize: 'Select size',

        // Footer
        footerDesc: 'Vietnam\'s leading luxury fashion rental platform. Experience high-end style at reasonable costs.',
        support: 'Support',
        contact: 'Contact',
        copyright: '© 2024 LUXE RENT. All rights reserved.',
        terms: 'Terms of Use',
        privacy: 'Privacy Policy',
        howToRent: 'How to Rent',
        returnPolicy: 'Return Policy',
        sizeGuide: 'Size Guide',
        faq: 'FAQ',
        
        // Colors
        color_blue: 'Blue',

        // Category Data Mapping
        'Váy cưới': 'Wedding Dresses',
        'Đầm dạ hội': 'Evening Gowns',
        'Vest nam': 'Men\'s Suits',
        'Vest sang trọng': 'Luxury Suits',
        'Phụ kiện': 'Accessories',
        'Giày & Sneaker': 'Shoes & Sneakers',
        'Thời trang nữ': 'Women\'s Fashion',
        'Thời trang nam': 'Men\'s Fashion',
        'Hàng mới về': 'New Arrivals',
        'Sản phẩm': 'Product',
        'Danh mục': 'Category',
        'Váy': 'Dresses',
        'Vest': 'Suits',
        'Sneaker': 'Sneakers',
        'Streetwear': 'Streetwear',
        'footerAddress': '123 Nguyen Hue St, Dist 1, HCMC',
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(localStorage.getItem('language') || 'vi');

    useEffect(() => {
        localStorage.setItem('language', language);
    }, [language]);

    const toggleLanguage = () => {
        setLanguage((prev) => (prev === 'vi' ? 'en' : 'vi'));
    };

    const t = (key, params = {}) => {
        let translation = translations[language][key] || key;
        
        // Check if any param is a React element
        const hasReactElements = Object.values(params).some(val => React.isValidElement(val));
        
        if (hasReactElements) {
            // Split by placeholders and interleave with param values
            const parts = translation.split(/(\{[^}]+\})/g);
            return parts.map((part, index) => {
                const match = part.match(/^\{([^}]+)\}$/);
                if (match) {
                    const paramName = match[1];
                    return params[paramName] !== undefined ? params[paramName] : part;
                }
                return part;
            });
        }

        // Handle string parameters (e.g., {count})
        Object.keys(params).forEach(param => {
            translation = translation.replace(`{${param}}`, params[param]);
        });
        
        return translation;
    };

    return (
        <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
